export const ActionTypes = {
    GET_CATEGORY_LIST: "GET_CATEGORY_LIST",
    SET_CATEGORY: "SET_CATEGORY",
    SET_SEARCH_VALUE: "SET_SEARCH_VALUE",
    GET_RANDOM_JOKE: "GET_RANDOM_JOKE",
    GET_NEXT_JOKE: "GET_NEXT_JOKE",
    SET_ERROR: "SET_ERROR"
}